---
stages: 
  - Build
  - Test

Build:
  stage: Build
  script:
    - npm run build

Code Validation:
  stage: Test
  dependencies: 
    - Build
  script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
