---
image: node:8.11.3

cache:
  paths:
  - node_modules/

stages: 
  - Build
  - Test

Build:
  stage: Build
  script:
    - npm install
    - npm run build

Code Validation:
  stage: Test
  dependencies: 
    - Build
  script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
